import type { Metadata } from "next";
import { Raleway } from "next/font/google"; // Changed from Open_Sans to Raleway
import "./globals.css";
import Layout from "@/components/Layout";
import Providers from "./providers";
import { ThemeProvider } from "./theme-provider";
import { Toaster } from "@/components/ui/toaster";
import Footer from "../components/Footer";

const raleway = Raleway({
  weight: ['300', '400', '500', '700'], 
  subsets: ["latin"],
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={raleway.className}>
        <Providers>
          <ThemeProvider
            attribute="class"
            disableTransitionOnChange
          >
            <Layout>{children}</Layout>
          </ThemeProvider>
          <Toaster />
        </Providers>
        <Footer />
      </body>
    </html>
  );
}
